### ISSUE TITLE
Can't install package 

### ISSUE THREAD

**Issue by szybnev** [sterrasec/dummy#4]
Can't install package 

![image](https://github.com/sterrasec/dummy/assets/32132485/c2fc50d1-46e2-4977-b7eb-5f79ee118900)

```bash
uname -a
Linux kali 6.6.9-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.6.9-1kali1 (2024-01-08) x86_64 GNU/Linux
```

**Comment by tkmru** [comment]
I see the same problem as in the following article.
[Error: Permission denied (publickey) - GitHub Docs](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey)

Please inspect your SSH connection for problems. Have you registered your SSH public key with GitHub?
